"""update in department table

Revision ID: 597df6489980
Revises: 1a87e88c94c8
Create Date: 2024-11-06 11:57:57.787789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '597df6489980'
down_revision: Union[str, None] = '1a87e88c94c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('departments', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('departments', sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('departments', sa.Column('modified_by', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'modified_by')
    op.drop_column('departments', 'modified_at')
    op.drop_column('departments', 'created_by')
    op.drop_column('departments', 'created_at')
    # ### end Alembic commands ###
